export const GET_FUTURE = "GET_FUTURE"
export const GET_FUTURE_SUCCESS = "GET_FUTURE_SUCCESS"
export const GET_FUTURE_FAIL = "GET_FUTURE_FAIL"

export const ADD_FUTURE = "ADD_FUTURE"
export const ADD_FUTURE_SUCCESS = "ADD_FUTURE_SUCCESS"
export const ADD_FUTURE_FAIL = "ADD_FUTURE_FAIL"

export const UPDATE_FUTURE = "UPDATE_FUTURE"
export const UPDATE_FUTURE_SUCCESS = "UPDATE_FUTURE_SUCCESS"
export const UPDATE_FUTURE_FAIL = "UPDATE_FUTURE_FAIL"

export const GET_FUTURE_INFO = "GET_FUTURE_INFO"
export const GET_FUTURE_INFO_SUCCESS = "GET_FUTURE_INFO_SUCCESS"
export const GET_FUTURE_INFO_FAIL = "GET_FUTURE_INFO_FAIL"

export const DELETE_FUTURE = "DELETE_FUTURE"
export const DELETE_FUTURE_SUCCESS = "DELETE_FUTURE_SUCCESS"
export const DELETE_FUTURE_FAIL = "DELETE_FUTURE_FAIL"