export const ADD_TECHNOLOGY = "ADD_TECHNOLOGY"
export const ADD_TECHNOLOGY_SUCCESS = "ADD_TECHNOLOGY_SUCCESS"
export const ADD_TECHNOLOGY_FAIL = "ADD_TECHNOLOGY_FAIL"

export const GET_TECHNOLOGY = "GET_TECHNOLOGY"
export const GET_TECHNOLOGY_SUCCESS = "GET_TECHNOLOGY_SUCCESS"
export const GET_TECHNOLOGY_FAIL = "GET_TECHNOLOGY_FAIL"

export const UPDATE_TECHNOLOGY = "UPDATE_TECHNOLOGY"
export const UPDATE_TECHNOLOGY_SUCCESS = "UPDATE_TECHNOLOGY_SUCCESS"
export const UPDATE_TECHNOLOGY_FAIL = "UPDATE_TECHNOLOGY_FAIL"

export const GET_TECHNOLOGY_INFO = "GET_TECHNOLOGY_INFO"
export const GET_TECHNOLOGY_INFO_SUCCESS = "GET_TECHNOLOGY_INFO_SUCCESS"
export const GET_TECHNOLOGY_INFO_FAIL = "GET_TECHNOLOGY_INFO_FAIL"

export const DELETE_TECHNOLOGY = "DELETE_TECHNOLOGY"
export const DELETE_TECHNOLOGY_SUCCESS = "DELETE_TECHNOLOGY_SUCCESS"
export const DELETE_TECHNOLOGY_FAIL = "DELETE_TECHNOLOGY_FAIL"
