
export const GET_CAREER = "GET_CAREER"
export const GET_CAREER_SUCCESS = "GET_CAREER_SUCCESS"
export const GET_CAREER_FAIL = "GET_CAREER_FAIL"

export const ADD_CAREER = "ADD_CAREER"
export const ADD_CAREER_SUCCESS = "ADD_CAREER_SUCCESS"
export const ADD_CAREER_FAIL = "ADD_CAREER_FAIL"

export const UPDATE_CAREER = "UPDATE_CAREER"
export const UPDATE_CAREER_SUCCESS = "UPDATE_CAREER_SUCCESS"
export const UPDATE_CAREER_FAIL = "UPDATE_CAREER_FAIL"

export const GET_CAREER_INFO = "GET_CAREER_INFO"
export const GET_CAREER_INFO_SUCCESS = "GET_CAREER_INFO_SUCCESS"
export const GET_CAREER_INFO_FAIL = "GET_CAREER_INFO_FAIL"

export const DELETE_CAREER = "DELETE_CAREER"
export const DELETE_CAREER_SUCCESS = "DELETE_CAREER_SUCCESS"
export const DELETE_CAREER_FAIL = "DELETE_CAREER_FAIL"