export const GET_CAREERFORM = "GET_CAREERFORM"
export const GET_CAREERFORM_SUCCESS = "GET_CAREERFORM_SUCCESS"
export const GET_CAREERFORM_FAIL = "GET_CAREERFORM_FAIL"

export const ADD_CAREERFORM = "ADD_CAREERFORM"
export const ADD_CAREERFORM_SUCCESS = "ADD_CAREERFORM_SUCCESS"
export const ADD_CAREERFORM_FAIL = "ADD_CAREERFORM_FAIL"

export const UPDATE_CAREERFORM = "UPDAE_CAREERFORM"
export const UPDATE_CAREERFORM_SUCCESS = "UPDATE_CAREERFORM_SUCCESS"
export const UPDATE_CAREERFORM_FAIL = "UPDATE_CAREERFORM_FAIL"

export const GET_CAREERFORM_INFO = "GET_CAREERFORM_INFO"
export const GET_CAREERFORM_INFO_SUCCESS = "GET_CAREERFORM_INFO_SUCCESS"
export const GET_CAREERFORM_INFO_FAIL = "GET_CAREERFORM_INFO_FAIL"

export const DELETE_CAREERFORM = "DELETE_CAREERFORM"
export const DELETE_CAREERFORM_SUCCESS = "DELETE_CAREERFORM_SUCCESS"
export const DELETE_CAREERFORM_FAIL = "DELETE_CAREERFORM_FAIL"
  