export const GET_TALENT_FAQ = "GET_TALENT_FAQ"
export const GET_TALENTFAQ_SUCCESS = "GET_TALENTFAQ_SUCCESS"
export const GET_TALENTFAQ_FAIL = "GET_TALENTFAQ_FAIL"

export const ADD_TALENTFAQ = "ADD_TALENTFAQ"
export const ADD_TALENTFAQ_SUCCESS = "ADD_TALENTFAQ_SUCCESS"
export const ADD_TALENTFAQ_FAIL = "ADD_TALENTFAQ_FAIL"

export const UPDATE_TALENTFAQ = "UPDAE_TALENTFAQ"
export const UPDATE_TALENTFAQ_SUCCESS = "UPDATE_TALENTFAQ_SUCCESS"
export const UPDATE_TALENTFAQ_FAIL = "UPDATE_TALENTFAQ_FAIL"

export const GET_TALENTFAQ_INFO = "GET_TALENTFAQ_INFO"
export const GET_TALENTFAQ_INFO_SUCCESS = "GET_TALENTFAQ_INFO_SUCCESS"
export const GET_TALENTFAQ_INFO_FAIL = "GET_TALENTFAQ_INFO_FAIL"

export const DELETE_TALENTFAQ = "DELETE_TALENTFAQ"
export const DELETE_TALENTFAQ_SUCCESS = "DELETE_TALENTFAQ_SUCCESS"
export const DELETE_TALENTFAQ_FAIL = "DELETE_TALENTFAQ_FAIL"
  